language: php
dist: bionic
sudo: required
services:
  - couchdb
php:
  - 7.1

before_script:
  - curl -X PUT localhost:5984/unittest
  - composer self-update
  - composer install --prefer-source --no-interaction --dev

script: vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)
